# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='character',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='updated',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
    ]
