# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20160801_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='template',
            field=models.CharField(choices=[('dnd_5e', 'Dungeons and Dragons 5th Edition')], default='dnd_5e', max_length=200),
            preserve_default=False,
        ),
    ]
