# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='template',
            new_name='game_template',
        ),
    ]
